CREATE OR REPLACE TABLE `produccion.Analisis_bases_Conciliaciones` AS
WITH concat_ticket_info AS (
    SELECT *, 
        CASE 
            WHEN TIPO = 'ACSELX' THEN
                CONCAT(CODPROD, '-', NUMPOL, '-',NUMCERT)
            ELSE
                CONCAT(CODPROD, '-', NUMPOL)
        END AS CONCATENADO, 
        CONCAT(SUBSTR(CERTIFICADO_BANCO, 1,4), SUBSTR(CERTIFICADO_BANCO, 7,2), SUBSTR(CERTIFICADO_BANCO, 11,10)) AS CERT_ID        
    FROM (
            SELECT DISTINCT *
            FROM `produccion.TICKET_INFORMACION_temp`
            #FROM `produccion.TICKET_INFORMACION`
        )
),
nros_las AS (
    SELECT
    CONCATENADO,
    COUNT(NRO_LA) AS CANT_LA,
    SUM(MONTO) AS SUM_MONTOS_LA,
    STRING_AGG(CAST(NRO_LA AS STRING), ', ') AS CONCAT_NROS_LA,
    STRING_AGG(CAST(MONTO AS STRING), ', ') AS CONCAT_MONTOS,
    STRING_AGG(CAST(ESTADO_ACTUAL AS STRING), ', ') AS CONCAT_ESTADOS,
    STRING_AGG(CAST(NUMOPER AS STRING), ', ') AS CONCAT_NUM_OPER
  FROM `produccion.REPORTE_LA`
  GROUP BY CONCATENADO
),
resumen AS(
    SELECT B.CERTIFICADO_BANCO, TRIM(T.CODPROD) AS COD_PROD, B.MONEDA, B.PRIMA AS MONTO_DEVOLVER, T.IDEPOL, T.CONCATENADO,
        U.PRODUCTO, T.STSCERT, T.FECHA_INICIO_VIGENCIA, T.FECHA_INI_ULT_COBERTURA, T.FECHA_FIN_ULT_COBERTURA, 
        U.FECHA_INICIO AS FECHA_INICIO_ULT_PAGO,
        T.DOC_ANU_INC, T.DOC_ESTADO_ANU_INC, T.PRIMA_INC_ANU, 
        T.PRIMA_COB, T.CAN_LQ_COB, T.CAN_LQ_INC, T.CAN_LQ_ANU, T.CAN_LQ_EMI,
        ROUND((PRIMA_COB * CAN_LQ_COB),2) AS PRIMA_TOTAL, 
        ROUND((PRIMA - (PRIMA_COB * CAN_LQ_COB)),2) AS DIFERENCIA_TOTAL,
        (PRIMA - L.SUM_MONTOS_LA) AS DIF_LA,
        CASE 
            WHEN T.CODMONEDA = 'SOL' THEN 'PEN'
            ELSE T.CODMONEDA
        END AS MONEDA_TICKET,
        CASE
            WHEN CANT_LA IS NOT NULL THEN CANT_LA
            ELSE 0
        END AS CANTIDAD_LA,
        CASE
            WHEN SUM_MONTOS_LA IS NOT NULL THEN ROUND(SUM_MONTOS_LA,2)
            ELSE 0
        END AS SUMA_MONTO_LA,
        CONCAT_NROS_LA, CONCAT_MONTOS, CONCAT_ESTADOS, CONCAT_NUM_OPER,
        T.STSSIN, B.FECHA_OPERACION, CALCULO_PRIMA,
        B.FECHA_OPERACION BETWEEN T.FECHA_INICIO_VIGENCIA AND T.FECHA_FIN_ULT_COBERTURA AS EN_COBERTURA,
        ROW_NUMBER() OVER ( PARTITION BY B.CERTIFICADO_BANCO, B.FECHA_OPERACION
            ORDER BY
                CASE
                    WHEN B.FECHA_OPERACION BETWEEN T.FECHA_INICIO_VIGENCIA AND T.FECHA_FIN_ULT_COBERTURA
                        THEN 1
                    ELSE 2
                END,
                T.FECHA_INICIO_VIGENCIA DESC
        ) AS NRO_REG

    #FROM `produccion.BASES_CONCILIACION` B 
    FROM `produccion.BASES_CONCILIACION_temp` B
    LEFT JOIN concat_ticket_info T ON CONCAT(SUBSTR(B.CERTIFICADO_BANCO, 1,4), SUBSTR(B.CERTIFICADO_BANCO, 7,2), 
                                        SUBSTR(B.CERTIFICADO_BANCO, 11,10))= T.CERT_ID
                                      
    LEFT JOIN nros_las L ON T.CONCATENADO = L.CONCATENADO
    LEFT JOIN `produccion.ULTIMOS_PAGOS_temp` U ON
                CONCAT(SUBSTR(B.CERTIFICADO_BANCO, 1,4), SUBSTR(B.CERTIFICADO_BANCO, 7,2),
                SUBSTR(B.CERTIFICADO_BANCO, 11,10))= U.CERT_ID

),
Detalles AS(
    SELECT CERTIFICADO_BANCO, MONEDA, FECHA_OPERACION, MONTO_DEVOLVER, IDEPOL, CONCATENADO,
            PRODUCTO, STSCERT, FECHA_INICIO_VIGENCIA, DATE(FECHA_INI_ULT_COBERTURA) AS FECHA_INI_ULT_COBERTURA, 
            FECHA_FIN_ULT_COBERTURA, FECHA_INICIO_ULT_PAGO,
            DOC_ANU_INC, DOC_ESTADO_ANU_INC, PRIMA_INC_ANU,
            PRIMA_COB, CAN_LQ_COB, CAN_LQ_INC, CAN_LQ_ANU, CAN_LQ_EMI,
            PRIMA_TOTAL, DIFERENCIA_TOTAL, CONCAT_NROS_LA, 
            CONCAT_MONTOS, SUMA_MONTO_LA, ROUND(DIF_LA,2) AS DIF_LA, 
            CONCAT_ESTADOS, CANTIDAD_LA, CONCAT_NUM_OPER, STSSIN, EN_COBERTURA, MONEDA_TICKET, CALCULO_PRIMA,
            CASE
                WHEN MONEDA != MONEDA_TICKET THEN 'ERROR EN MONEDA'
                WHEN CANTIDAD_LA > 0 AND CONCAT_ESTADOS LIKE '%ACT%' THEN
                    CASE 
                        WHEN MONEDA = 'PEN' AND DIF_LA BETWEEN -1 AND 1 THEN 'ENVIAR A COBRANZAS'
                        WHEN MONEDA = 'USD' AND DIF_LA BETWEEN -0.5 AND 0.5 THEN 'ENVIAR A COBRANZAS'
                        WHEN MONEDA = 'PEN' AND DIF_LA NOT BETWEEN -1 AND 1 AND 
                                        COD_PROD IN ('1355','1365','1403','1422') THEN 'POLIZA CON REASEGURO'
                        WHEN MONEDA = 'USD' AND DIF_LA NOT BETWEEN -0.5 AND 0.5 AND 
                                        COD_PROD IN ('1355','1365','1403','1422') THEN 'POLIZA CON REASEGURO'
                        WHEN MONEDA = 'PEN' AND DIF_LA NOT BETWEEN -1 AND 1 THEN
                            CASE 
                                WHEN PRIMA_TOTAL >= MONTO_DEVOLVER THEN 'AJUSTAR LA'
                                ELSE "FALTA MONTO EMITIDO"
                            END
                        WHEN MONEDA = 'USD' AND DIF_LA NOT BETWEEN -0.5 AND 0.5 THEN 
                            CASE 
                                WHEN PRIMA_TOTAL >= MONTO_DEVOLVER THEN 'AJUSTAR LA'
                                ELSE "FALTA MONTO EMITIDO"
                            END
                    END
                WHEN CANTIDAD_LA > 0 AND CONCAT_ESTADOS LIKE '%PAG%' THEN 'LA PAGADA'
                WHEN CANTIDAD_LA > 0 AND CONCAT_ESTADOS LIKE '%OPT%' THEN 'LA OPT'
                WHEN CANTIDAD_LA > 0 AND CONCAT_ESTADOS LIKE '%CMP%' THEN 'LA CMP'
                WHEN CANTIDAD_LA > 0 AND CONCAT_ESTADOS LIKE '%PGP%' THEN 'LA PGP'

                WHEN MONTO_DEVOLVER <= PRIMA_TOTAL THEN 
                    CASE                                                          
                        WHEN STSCERT = 'ACT' AND CANTIDAD_LA = 0 AND CAN_LQ_INC = 0 AND 
                                            CAN_LQ_ANU > 0 THEN 'ANULACION CON LQ ANULADAS'
                                        
                        WHEN STSCERT = 'ANU' AND CANTIDAD_LA = 0 AND CAN_LQ_INC = 0 AND 
                                            CAN_LQ_ANU > 0 THEN 'REHABILITACION CON LQ ANULADAS'

                        WHEN STSCERT IN ('ACT','ANU') AND CAN_LQ_INC > 0 AND CANTIDAD_LA = 0 
                                                        AND CAN_LQ_COB= 0 AND CAN_LQ_ANU = 0 THEN 'PAGOS EN INC'

                        WHEN STSCERT = 'ACT' AND CANTIDAD_LA = 0 AND CAN_LQ_INC = 0 AND CAN_LQ_ANU = 0 THEN 'ANULACION'

                        WHEN STSCERT = 'ANU' AND CANTIDAD_LA = 0 AND CAN_LQ_INC = 0 AND CAN_LQ_ANU = 0 THEN 'REHABILITACION'

                        WHEN STSCERT = 'REN' AND CANTIDAD_LA = 0 AND CAN_LQ_INC = 0 AND CAN_LQ_ANU = 0 THEN 'REN - ACT'

                        WHEN STSCERT = 'ACT' AND CANTIDAD_LA = 0 AND CAN_LQ_INC > 0 AND 
                                                                CAN_LQ_ANU >= 0 THEN 'ANULACION CON LQ ANULADAS Y LQ INC'
                        WHEN STSCERT = 'ANU' AND CANTIDAD_LA = 0 AND CAN_LQ_INC > 0 AND 
                                                                CAN_LQ_ANU >= 0 THEN 'REHABILITACION CON LQ ANULADAS Y LQ INC'
                        WHEN STSCERT = 'REN' AND CANTIDAD_LA = 0 AND CAN_LQ_INC > 0 AND 
                                                                CAN_LQ_ANU >= 0 THEN 'REN - ACT CON LQ ANULADAS Y LQ INC'

                    END          
                WHEN STSCERT = 'VAL' THEN 'POLIZA ESTADO VAL'
                WHEN STSCERT = 'EXC' THEN 'POLIZA ESTADO EXCLUIDO'
                        
                WHEN FECHA_INICIO_ULT_PAGO > FECHA_FIN_ULT_COBERTURA  THEN 'PENDIENTE EMITIR'

                WHEN STSCERT= 'ACT' AND PRIMA_INC_ANU >= MONTO_DEVOLVER AND CANTIDAD_LA = 0 AND CAN_LQ_ANU = 0 AND 
                                                                PRIMA_COB IS NULL THEN 'PENDIENTE APLICAR PAGOS'

                WHEN STSCERT= 'ANU' AND PRIMA_INC_ANU >= MONTO_DEVOLVER AND CANTIDAD_LA = 0 AND CAN_LQ_ANU = 0 AND 
                                                                PRIMA_COB IS NULL THEN 'REVERSAR ANULACION - APLICAR PAGOS'

                WHEN STSCERT= 'ANU' AND PRIMA_INC_ANU >= MONTO_DEVOLVER AND CANTIDAD_LA = 0 AND CAN_LQ_ANU > 0 AND 
                                                                CAN_LQ_INC = 0  AND PRIMA_COB IS NULL THEN 'REHABILITAR Y APLICAR PAGOS'

                WHEN STSCERT= 'ACT' AND PRIMA_INC_ANU >= MONTO_DEVOLVER AND CANTIDAD_LA = 0 AND CAN_LQ_ANU > 0 AND 
                                                    PRIMA_COB IS NULL THEN 'ANULAR INICO DE VIG - REHABILITAR Y APLICAR PAGOS'

                WHEN MONTO_DEVOLVER > PRIMA_TOTAL OR MONTO_DEVOLVER > PRIMA_INC_ANU THEN 'FALTA MONTO EMITIDO'
                WHEN STSSIN IS NOT NULL THEN 'POLIZA CON SINIESTRO' 
                WHEN IDEPOL IS NULL THEN 'NO SE ENCONTRO EN TICKET INFO'  
            END AS DETALLE
    FROM resumen
    WHERE NRO_REG= 1 OR IDEPOL IS NULL
)
SELECT *, 
    CASE
        WHEN DETALLE IN ('AJUSTAR LA', 'LA CMP', 'LA OPT', 
                            'LA PAGADA','LA PGP', 'POLIZA CON REASEGURO') THEN 'REVISIÓN PREVIA LAS'

        WHEN DETALLE IN ('ANULACION CON LQ ANULADAS', 
                            'ANULACION CON LQ ANULADAS Y LQ INC', 
                            'ANULAR INICO DE VIG - REHABILITAR Y APLICAR PAGOS',
                            'REHABILITACION CON LQ ANULADAS Y LQ INC', 
                            'REHABILITAR Y APLICAR PAGOS',
                            'REN - ACT CON LQ ANULADAS Y LQ INC',
                            'REVERSAR ANULACION - APLICAR PAGOS') THEN 'REVISIÓN PREVIA PARA PROCESAR'

        WHEN DETALLE IN ('ANULACION', 'ENVIAR A COBRANZAS', 'PAGOS EN INC', 
                            'PENDIENTE APLICAR PAGOS','REHABILITACION', 'REN - ACT') THEN 'LISTOS PARA PROCESAR'

        WHEN DETALLE IN ('FALTA MONTO EMITIDO', 'PENDIENTE EMITIR', 'POLIZA ESTADO VAL') THEN 'REVISIÓN PREVIA - EMISIÓN'

        WHEN DETALLE IN ('ERROR EN MONEDA', 'POLIZA CON SINIESTRO', 'POLIZA ESTADO EXCLUIDO') THEN 'DETALLES PARTICULARES'

        WHEN DETALLE = 'NO SE ENCONTRO EN TICKET INFO' THEN 'INFO NO UBICADA'
    END AS RESUMEN
FROM Detalles
